### ISSUE TITLE
A question about dual-softmax

### ISSUE THREAD

**Issue by Graysonggg** [cvg/GlueStick#14]
Hello, great job!

I noticed that you used sinkhorn algorithm in the matching phase of superglue, while dual-softmax is used in this paper. May I ask why they are similar in effect? Or is there any theoretical support? 

Looking forward to your reply very much!

**Comment by rpautrat** [comment]
Hi, yes SuperGlue was trained and released with the Sinkhorn algorithm. However, since then, several methods (such as LoFTR) opted for the double softmax instead, as it was faster and at least as good as Sinkhorn.

We don't have a theoretical proof for that, but we also observed a similar behavior for GlueStick, so we chose the double softmax.

**Comment by Graysonggg** [comment]
Appreciate for so quick reply.
